// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalesManagerBE.Data;

#nullable disable

namespace SalesManagerBE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824083144_AddContactInfo")]
    partial class AddContactInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalesManagerBE.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("SalesManagerBE.Models.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khánh Tân, Sài Sơn, Quốc Oai, Hà Nội",
                            Email = "info@vlxdpro.vn",
                            IsActive = true,
                            Phone = "0901 234 567",
                            WorkingHours = "Thứ 2 - Thứ 7: 7:00 - 18:00"
                        });
                });

            modelBuilder.Entity("SalesManagerBE.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsBusiness")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<bool>("FromAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("SalesInvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalesInvoiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SalesManagerBE.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("UnitTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.HasIndex("UnitTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Xi măng",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Xi măng Portland PC40",
                            Price = 95000m,
                            ProductCode = "XM001",
                            ProductName = "Xi măng Hà Tiên PC40",
                            StockQuantity = 500m,
                            Unit = "Bao 50kg",
                            UnitTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Gạch",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gạch đất nung tiêu chuẩn",
                            Price = 2500m,
                            ProductCode = "GT001",
                            ProductName = "Gạch thẻ đặc 6x10x22",
                            StockQuantity = 10000m,
                            Unit = "Viên",
                            UnitTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cát - Đá",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cát vàng sạch",
                            Price = 250000m,
                            ProductCode = "CT001",
                            ProductName = "Cát vàng xây dựng",
                            StockQuantity = 200m,
                            Unit = "m³",
                            UnitTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Thép",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thép tròn xây dựng phi 10mm",
                            Price = 17500m,
                            ProductCode = "ST001",
                            ProductName = "Sắt thép tròn phi 10",
                            StockQuantity = 1500m,
                            Unit = "Kg",
                            UnitTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "Tôn - Mái",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tôn mạ kẽm dày 0.4mm",
                            Price = 85000m,
                            ProductCode = "TN001",
                            ProductName = "Tôn lạnh mạ kẽm 0.4mm",
                            StockQuantity = 800m,
                            Unit = "m²",
                            UnitTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Cửa - Khung",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cửa sắt hộp sơn tĩnh điện",
                            Price = 1800000m,
                            ProductCode = "CX001",
                            ProductName = "Cửa sắt hộp 2 cánh 1.2x2m",
                            StockQuantity = 50m,
                            Unit = "Bộ",
                            UnitTypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cát - Đá",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đá dăm 1x2 dùng trộn bê tông",
                            Price = 320000m,
                            ProductCode = "DA001",
                            ProductName = "Đá dăm 1x2 xây dựng",
                            StockQuantity = 300m,
                            Unit = "m³",
                            UnitTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sơn",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sơn nước cao cấp",
                            Price = 1250000m,
                            ProductCode = "SN001",
                            ProductName = "Sơn nước nội thất Jotun 18L",
                            StockQuantity = 120m,
                            Unit = "Thùng",
                            UnitTypeId = 7
                        });
                });

            modelBuilder.Entity("SalesManagerBE.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ShowOnHome")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Xi măng",
                            ShowOnHome = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gạch",
                            ShowOnHome = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cát - Đá",
                            ShowOnHome = true
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thép",
                            ShowOnHome = true
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tôn - Mái",
                            ShowOnHome = true
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cửa - Khung",
                            ShowOnHome = true
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sơn",
                            ShowOnHome = true
                        });
                });

            modelBuilder.Entity("SalesManagerBE.Models.ProductNameTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductNameTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Xi măng Hà Tiên PC40"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Xi măng Hà Tiên PCB30"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Xi măng INSEE PC40"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Gạch thẻ đặc 6x10x22"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Gạch thẻ rỗng 6x10x22"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Gạch block 10x20x40"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Cát vàng xây dựng"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Đá dăm 1x2"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Name = "Sắt thép tròn phi 10"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "Sắt thép tròn phi 12"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Name = "Tôn lạnh mạ kẽm 0.4mm"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Name = "Tôn màu 0.45mm"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Name = "Cửa sắt hộp 2 cánh"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Name = "Sơn nước nội thất Jotun 18L"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 7,
                            Name = "Sơn chống thấm Kova 20kg"
                        });
                });

            modelBuilder.Entity("SalesManagerBE.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("SalesManagerBE.Models.SalesInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreparedByName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SalesInvoices");
                });

            modelBuilder.Entity("SalesManagerBE.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("SalesInvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesInvoiceId");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("SalesManagerBE.Models.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UnitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bao 50kg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Viên"
                        },
                        new
                        {
                            Id = 3,
                            Name = "m³"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kg"
                        },
                        new
                        {
                            Id = 5,
                            Name = "m²"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bộ"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thùng"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tấm"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cái"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lít"
                        });
                });

            modelBuilder.Entity("SalesManagerBE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Conversation", b =>
                {
                    b.HasOne("SalesManagerBE.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Message", b =>
                {
                    b.HasOne("SalesManagerBE.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagerBE.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Order", b =>
                {
                    b.HasOne("SalesManagerBE.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("Orders")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SalesManagerBE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesInvoice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SalesManagerBE.Models.OrderItem", b =>
                {
                    b.HasOne("SalesManagerBE.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagerBE.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Product", b =>
                {
                    b.HasOne("SalesManagerBE.Models.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SalesManagerBE.Models.UnitType", "UnitType")
                        .WithMany("Products")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductCategory");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("SalesManagerBE.Models.ProductNameTemplate", b =>
                {
                    b.HasOne("SalesManagerBE.Models.ProductCategory", "Category")
                        .WithMany("ProductNameTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SalesManagerBE.Models.SalesInvoice", b =>
                {
                    b.HasOne("SalesManagerBE.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesManagerBE.Models.StockTransaction", b =>
                {
                    b.HasOne("SalesManagerBE.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagerBE.Models.SalesInvoice", "SalesInvoice")
                        .WithMany("Items")
                        .HasForeignKey("SalesInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");

                    b.Navigation("SalesInvoice");
                });

            modelBuilder.Entity("SalesManagerBE.Models.User", b =>
                {
                    b.HasOne("SalesManagerBE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Product", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SalesManagerBE.Models.ProductCategory", b =>
                {
                    b.Navigation("ProductNameTemplates");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SalesManagerBE.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SalesManagerBE.Models.SalesInvoice", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SalesManagerBE.Models.UnitType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
